project_id = "ejgxmkglklyumyycpvgi"


[functions.create-checkout-session]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = false

[functions.scheduled-bulk-search]
verify_jwt = false

[functions.scheduled-bulk-search-dispatcher]
verify_jwt = false

[functions.scheduled-market-offering-search]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

