project_id = "ejgxmkglklyumyycpvgi"

[functions.getSingleRoute]
verify_jwt = false

[functions.getRoundTripRoute]
verify_jwt = false

[functions.getAllDestinations]
verify_jwt = false

[functions.getAllDirects]
verify_jwt = false

[functions.scheduledATLSnapshot]
verify_jwt = false

[functions.airlabsRoutes]
verify_jwt = false

[functions.airlabsSchedules]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = false
