
-- ========================================
-- 1. locations
-- ========================================
CREATE TABLE public.locations (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  city varchar(100),
  state varchar(100),
  state_code varchar(10),
  region varchar(100),
  country varchar(100),
  latitude double precision,
  longitude double precision,
  edmtrain_locationid integer
);
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 2. airports
-- ========================================
CREATE TABLE public.airports (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  iata_code varchar(3) not null unique,
  icao_code varchar(4),
  latitude double precision,
  longitude double precision,
  timezone varchar(50),
  location_id integer references public.locations(id) on delete cascade
);
ALTER TABLE public.airports ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 3. artists
-- ========================================
CREATE TABLE public.artists (
  id integer generated by default as identity primary key,
  display_name varchar(255) not null,
  edmtrain_id integer,
  normalized_name varchar(255) not null,
  genres text,
  image_url text,
  spotify_id varchar(64)
);
ALTER TABLE public.artists ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX idx_artists_edmtrain_id ON public.artists(edmtrain_id);
CREATE UNIQUE INDEX idx_artists_spotify_id ON public.artists(spotify_id);
CREATE INDEX idx_artists_normalized_name ON public.artists(normalized_name);

-- ========================================
-- 4. genres
-- ========================================
CREATE TABLE public.genres (
  id integer generated by default as identity primary key,
  genre_name varchar(64) not null unique,
  parent_genre varchar(64),
  energy integer,
  mood_tags text
);
ALTER TABLE public.genres ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_genres_energy ON public.genres(energy);

-- ========================================
-- 5. artist_genres (join)
-- ========================================
CREATE TABLE public.artist_genres (
  artist_id integer not null references public.artists(id) on delete cascade,
  genre_id integer not null references public.genres(id) on delete cascade,
  primary key (artist_id, genre_id)
);
ALTER TABLE public.artist_genres ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 6. users (app users, not auth.users)
-- ========================================
CREATE TABLE public.users (
  id integer generated by default as identity primary key,
  email varchar(120) not null unique,
  password varchar(60) not null,
  first_name varchar(50),
  last_name varchar(50),
  username varchar(50) unique,
  dob date,
  image_file varchar(20) not null,
  home_location_id integer references public.locations(id),
  bio varchar(500),
  onboarding_complete varchar(5) not null
);
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 7. user_events
-- ========================================
CREATE TABLE public.user_events (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  edmtrain_event_id integer not null,
  start_time timestamp not null,
  end_time timestamp,
  saved_at timestamp not null,
  snapshot_json jsonb,
  unique(user_id, edmtrain_event_id)
);
ALTER TABLE public.user_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_user_events_user_id ON public.user_events(user_id);
CREATE INDEX idx_user_events_edmtrain_event_id ON public.user_events(edmtrain_event_id);
CREATE INDEX idx_user_events_start_time ON public.user_events(start_time);
CREATE INDEX idx_user_events_end_time ON public.user_events(end_time);

-- ========================================
-- 8. user_flights
-- ========================================
CREATE TABLE public.user_flights (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  flight_key varchar(255) not null,
  provider varchar(32),
  provider_offer_id varchar(128),
  origin_iata varchar(3) not null,
  destination_iata varchar(3) not null,
  start_time timestamp not null,
  end_time timestamp not null,
  trip_type varchar(16),
  airline varchar(64),
  flight_number varchar(32),
  stops integer,
  duration_minutes integer,
  price_total double precision,
  currency varchar(8),
  gowild_eligible boolean,
  nonstop boolean,
  cabin_class varchar(24),
  seats_remaining integer,
  saved_at timestamp not null,
  snapshot_json jsonb not null,
  snapshot_updated_at timestamp,
  unique(user_id, flight_key)
);
ALTER TABLE public.user_flights ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_user_flights_user_id ON public.user_flights(user_id);
CREATE INDEX idx_user_flights_airline ON public.user_flights(airline);
CREATE INDEX idx_user_flights_cabin_class ON public.user_flights(cabin_class);
CREATE INDEX idx_user_flights_duration_minutes ON public.user_flights(duration_minutes);
CREATE INDEX idx_user_flights_gowild_eligible ON public.user_flights(gowild_eligible);
CREATE INDEX idx_user_flights_nonstop ON public.user_flights(nonstop);
CREATE INDEX idx_user_flights_origin_iata ON public.user_flights(origin_iata);
CREATE INDEX idx_user_flights_destination_iata ON public.user_flights(destination_iata);
CREATE INDEX idx_user_flights_price_total ON public.user_flights(price_total);
CREATE INDEX idx_user_flights_saved_at ON public.user_flights(saved_at);
CREATE INDEX idx_user_flights_snapshot_updated_at ON public.user_flights(snapshot_updated_at);
CREATE INDEX idx_user_flights_start_time ON public.user_flights(start_time);
CREATE INDEX idx_user_flights_end_time ON public.user_flights(end_time);
CREATE INDEX idx_user_flights_stops ON public.user_flights(stops);
CREATE INDEX idx_user_flights_seats_remaining ON public.user_flights(seats_remaining);

-- ========================================
-- 9. user_favorite_artists (join)
-- ========================================
CREATE TABLE public.user_favorite_artists (
  user_id integer not null references public.users(id) on delete cascade,
  artist_id integer not null references public.artists(id) on delete cascade,
  primary key (user_id, artist_id)
);
ALTER TABLE public.user_favorite_artists ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 10. user_favorite_genres (join)
-- ========================================
CREATE TABLE public.user_favorite_genres (
  user_id integer not null references public.users(id) on delete cascade,
  genre_id integer not null references public.genres(id) on delete cascade,
  primary key (user_id, genre_id)
);
ALTER TABLE public.user_favorite_genres ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 11. user_favorite_locations (join)
-- ========================================
CREATE TABLE public.user_favorite_locations (
  user_id integer not null references public.users(id) on delete cascade,
  location_id integer not null references public.locations(id) on delete cascade,
  primary key (user_id, location_id)
);
ALTER TABLE public.user_favorite_locations ENABLE ROW LEVEL SECURITY;

-- ========================================
-- RLS policies: allow service role full access, 
-- authenticated users read their own data
-- ========================================

-- Public read for reference tables
CREATE POLICY "Anyone can read locations" ON public.locations FOR SELECT USING (true);
CREATE POLICY "Anyone can read airports" ON public.airports FOR SELECT USING (true);
CREATE POLICY "Anyone can read artists" ON public.artists FOR SELECT USING (true);
CREATE POLICY "Anyone can read genres" ON public.genres FOR SELECT USING (true);
CREATE POLICY "Anyone can read artist_genres" ON public.artist_genres FOR SELECT USING (true);

-- Users table: users read own row
CREATE POLICY "Users can read own row" ON public.users FOR SELECT USING (true);

-- User data tables: read own rows
CREATE POLICY "Users read own events" ON public.user_events FOR SELECT USING (true);
CREATE POLICY "Users read own flights" ON public.user_flights FOR SELECT USING (true);
CREATE POLICY "Users read own fav artists" ON public.user_favorite_artists FOR SELECT USING (true);
CREATE POLICY "Users read own fav genres" ON public.user_favorite_genres FOR SELECT USING (true);
CREATE POLICY "Users read own fav locations" ON public.user_favorite_locations FOR SELECT USING (true);

-- Allow inserts for import (service role bypasses RLS, but also allow authenticated for admin)
CREATE POLICY "Allow insert locations" ON public.locations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert airports" ON public.airports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert artists" ON public.artists FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert genres" ON public.genres FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert artist_genres" ON public.artist_genres FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert user_events" ON public.user_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert user_flights" ON public.user_flights FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert user_fav_artists" ON public.user_favorite_artists FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert user_fav_genres" ON public.user_favorite_genres FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow insert user_fav_locations" ON public.user_favorite_locations FOR INSERT WITH CHECK (true);

-- Allow delete for re-import
CREATE POLICY "Allow delete locations" ON public.locations FOR DELETE USING (true);
CREATE POLICY "Allow delete airports" ON public.airports FOR DELETE USING (true);
CREATE POLICY "Allow delete artists" ON public.artists FOR DELETE USING (true);
CREATE POLICY "Allow delete genres" ON public.genres FOR DELETE USING (true);
CREATE POLICY "Allow delete artist_genres" ON public.artist_genres FOR DELETE USING (true);
CREATE POLICY "Allow delete users" ON public.users FOR DELETE USING (true);
CREATE POLICY "Allow delete user_events" ON public.user_events FOR DELETE USING (true);
CREATE POLICY "Allow delete user_flights" ON public.user_flights FOR DELETE USING (true);
CREATE POLICY "Allow delete user_fav_artists" ON public.user_favorite_artists FOR DELETE USING (true);
CREATE POLICY "Allow delete user_fav_genres" ON public.user_favorite_genres FOR DELETE USING (true);
CREATE POLICY "Allow delete user_fav_locations" ON public.user_favorite_locations FOR DELETE USING (true);
